server:
  port: 8080    
     
banner:
  location : classpath:banner-bpm.txt
  #image.location : /static/img/greenfence.png
  #text: [[ greenfence ]) - BPM
  #renderer: http://patorjk.com/software/taag/#p=display&f=Big&t=%5B%5B%20greenfence%20%5D)%20-%20BPM

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf_demo?useSSL=false
    username: root
    password: root
    
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto : update
  activiti:
    checkProcessDefinitions : false
  
sso:
  server : http://10.10.30.199:28081/auth
  client-id: greenfence  
  client-secret:  greenfence$123
  scopes: openid
  redirect-uri: http://localhost:30110
  
payments:
  uri: http://localhost:9091

notifications:
  amqp:
    notifications-queue: bpm-anab-auditors
    
---

spring:
  profiles: cloud
 
auditors:
  ui:
     links:
       home: http://microservicesdev.greenfence.com
       sso: http://greenfence-sso-gateway-dev.cfapps.io
       payments: http://greenfence-payments-gateway-dev.cfapps.io
       documents: http://greenfence-documents-gateway-dev.cfapps.io
       notifications: http://greenfence-notifications-gateway-dev.cfapps.io
       messaging: http://greenfence-messaging-gateway-dev.cfapps.io 
sso:
  server : https://greenfence-sso-gateway-dev.cfapps.io/
  redirect-uri: https://greenfence-bpm-anab-audits.cfapps.io
  
  
payments:
  uri: https://greenfence-payments-gateway-dev.cfapps.io/
  
notifications:
  uri:  http://greenfence-notifications-gateway-dev.cfapps.io
   