spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf_demo?useSSL=false
    username: root
    password: root
    
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto : update
  activiti:
    checkProcessDefinitions : false

server:
  port: 8080
  session:
    timeout: 99999

sso:
  server : http://localhost:28081/auth
  client-id: greenfence  
  client-secret:  greenfence$123
  scopes: openid
  redirect-uri: http://localhost:30110